### ISSUE TITLE
국내 커뮤니티 사이트 streamer 클래스 추가

### ISSUE THREAD

**Issue by nyanye** [koshort/koshort#1]
- [x] DCInsideStreamer (거의 완료)
- [ ] ClienStreamer (클리앙, 예정)
- [ ] PpomppuStreamer (뽐뿌, 예정)
- [ ] HumorUnivStreamer (웃대, 예정)
- [ ] RuriWebStreamer (루리웹, 예정)

* ...?

**Comment by BbChip0103** [comment]
안녕하세요~
프로젝트 시작 계기나 방향 등이 저와 뜻이 맞는 부분이 많아서 글 남기게 되었습니다.
주요 대상은 구어체 수집인듯 하지만, 다른 것도 괜찮다면 저도 여러가지 기여할 수 있을 듯 합니다.

현재까지 생각해본 목록은 다음과 같습니다.
* 다음 실시간 인기검색어
* 구글 트렌드
RSS 피드 기준으로 가져올 생각입니다.
* 조선, 중앙, 동아일보 최신기사 혹은 입력 키워드에 따른 결과 수집
* 유튜브 실시간 인기 동영상 목록
* 네이버 인기검색어 개선
네이버 데이터랩에서 지난 날짜의 인기검색어 순위나, 특정 키워드의 날짜 별 순위 변동 추이를 가져올 수 있을 듯 합니다. 
* 출력 형태 개선
단순 문자열 형태가 아닌, csv, xlsx, json, xml, pkl등으로 출력할 수 있게 하면 좋을 듯 합니다.
생각보다 엑셀로 데이터 분석하시는 분들이 많으시더라구요;;

혹시 추가할 점이나 문제될 점이 있다면 말씀해주시고, 괜찮으시다면 위에서부터 하나씩 작업해보겠습니다! ^^

**Comment by nyanye** [comment]
좋은 피드백 감사합니다!
사실 이 프로젝트의 제일 처음 시작점은 트위터 실시간 스트리밍 하나만을 위해서 짜던 코드를 확장한 형태라서 정확한 방향성이 정해져있지 않았었기에 무엇이든 좋은 건 넣고 싶다는 생각이네요 ㅎㅎ
제가 생각했던 기본적인 컨셉은,

* "여기에서 여기까지 수집하자!" 보단 한 번 시작하면 별 다른 문제가 생기기 전까지 계속해서 수집하는 스트리밍 형식
* 파이썬 패키지로도 사용 가능하지만 커맨드라인 한 줄로도 사용 가능
* 로컬 경로의 data 폴더 안에 라이브러리를 이용해 수집한 데이터를 어떻게든 축적
* 과거의 데이터도 긁어올 수 있으면 좋지만 현재 구현된 API는 실시간만 가능(이 부분은 국내 커뮤니티 게시글에서는 개선 예정)
* 비동기 / 쓰레딩을 활용한 효율적인 스트리밍
* 지원 플랫폼 / 커뮤니티 등은 되는 대로 늘려보기 (말씀해주신 구글 트렌드, 다음 유튜브 등등 엄청 좋은 것 같네요!)

정도인데요! 다양한 출력 형태를 지원하는 부분같은 경우엔 csv, xlsx 컬럼 구분을 어떻게 해야할 지같은 문제들이 해결이 안돼서 잠깐 생각했다가 보류했었던 것 같네요 ㅠㅠ  
다 너무 좋은 기능 같고 pull request만 주신다면 검토하겠습니다!  
혹시 채팅이 필요하시다면 [이쪽](https://discordapp.com/invite/eNFUnZt)도 괜찮습니다 :)
